const JEST_TESTS_CONSTANTS ={
    EXISTING_USER_NICKNAME : 'skteam',
    NON_EXISTING_USER_NICKNAME : 'f9823h8nasd',
    EXISTING_CHALLENGE_DATA_UID : '0ETDj1qib2L6Dr2yBqx4',
    NON_EXISTING_CHALLENGE_DATA_UID : 'thisdoesnotexits',
    EXISTING_CHALLENGE_INDEX_UID : 'qrmP5bR9umGCQXdwKifr',
    DOCUMENT_NUMBER_LIMIT: 2,
    EXISTING_CATEGORY: 'History',
    EXISTING_USER_ID:'7vt3hVpztJda4rEMenfJyMr42U52',
    NON_EXISTING_USER_ID : '$$$$$',
}
export { JEST_TESTS_CONSTANTS }