const GAME_CONSTANTS ={
    SKPOINTS_AWARD_CHALLENGE_CREATION: 10,
    CHALLENGE_NUMBER_OF_GUESSES_ALLOWED: 5,
    CHALLENGE_TIMER_INITIAL_MINUTES: 5,
    CHALLENGE_TIMER_INITIAL_SECONDS: 0,
    CHALLENGE_SUCESSFULLY_SOLVED_MIN_AWARDED_POINTS: 10,
    CHALLENGE_FAILED__MIN_PENALIZED_POINTS: 5
}
export { GAME_CONSTANTS }